### ISSUE TITLE
Unable to share results from Wordle

### ISSUE THREAD

**Issue by ChaliceChore** [cylonid/NativeAlphaForAndroid#103]
[Wordle](https://www.nytimes.com/games/wordle/index.html) is a puzzle game acquired by The New York Times.
After solving the daily puzzle in a regular browser tab, a window pops up to share the results in other apps. However, in the Native Alpha web app, a message pops up saying **Share Failed**. Please fix this! :)
[Screenshot](https://i.imgur.com/E3Vmebe.png)

**Comment by cylonid** [comment]
@ChaliceChore I could not reproduce, sharing seems to work fine. Can you re-check? It is possible a WebView update fixed this in the meantime.

**Comment by ChaliceChore** [comment]
Sorry, I felt the app isn't is development anymore so I moved on to Hermit.
