### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by singhdilveer1** [cylonid/NativeAlphaForAndroid#104]
Thanks @cylonid for this amazing app. I have a few suggestions that you'll hopefully consider.

1. Making it so that people can choose from multiple favicons when creating a shortcut, like the webapp manager on Linux Mint. Downloading proper icons is a hassle and most people would rather use a slightly less quality one than having to download each of them individually.
2. Adding the ability to change/remove the splash and progress bar shown when opening a webapp. It just takes away the illusion of them being native apps.

**Comment by ChaliceChore** [comment]
I second both the requests.

**Comment by cylonid** [comment]
2. can be implemented easily, good idea.

About 1., I am not sure how useful this really is in practice. Could be done, but not a top priority for me at the moment.

**Comment by singhdilveer1** [comment]
Closing as "not planned" as there have been no updates from the owner.
