### ISSUE TITLE
Cannot open or download PDF file 

### ISSUE THREAD

**Issue by supernatural30** [cylonid/NativeAlphaForAndroid#106]
Using latest Github apk.

I made a shortcut for my health insurance provider site. On that site there is an option to view PDF files.

When I try to open the PDF, Native Alpha crashes.

I tried enabling all insecure options like http, third party cookies, and disabling all secure options like adblock, and also allow for opening third party links in browser.

Maybe an option to long press a link and choose "download" would fix the issue? Or allow for attachments to be opened in other apps?

Thanks.

**Comment by zhdenny** [comment]
I noticed downloads are basically not supported right now. App seems to crash whenever a download is initiated.

**Comment by LittleFreak** [comment]
You might try the share option for now.

**Comment by cylonid** [comment]
Downloads will be supported in the next release v1.4.0

**Comment by zhdenny** [comment]
Updated to latest release 1.4.0 and the App still crashes when a download is initiated. I don't see any real change.
