### ISSUE TITLE
Not able to sign in gmail

### ISSUE THREAD

**Issue by the-loan-wolf** [cylonid/NativeAlphaForAndroid#11]
Google is not allowing to sign in and giving message that browser is not secure/supported. Every site which uses gmail for login now I am not able to sign in in those site, if gmail login support come in native alpha then it will be really helpful for people with low specification phone

**Comment by cylonid** [comment]
@the-loan-wolf Login with Google account works for me, I just rechecked. Are you trying to log in to a Google service like Gmail, YouTube or a third-party page using Google authentication? Have you installed all updates for the WebView app?

**Comment by the-loan-wolf** [comment]
I tried to login in YouTube and gmail and I am using stock webview, OK I will try to update it and try again

**Comment by the-loan-wolf** [comment]
After using bromite system webview it's work you can now close this issue
