### ISSUE TITLE
Clipboard contents not available

### ISSUE THREAD

**Issue by deanaba** [cylonid/NativeAlphaForAndroid#119]
Clipboard contents obtained outside of webapp are unavailable within.
Native Alpha version 1.3.1
Env: Google Pixel 6 pro running Graphene, build TQ3A.230805.001.2023090600 (No GAPS installed)
Default system browser: fennec version 117.0.1

Replicate:

Copy plain text from any app to system's clipboard.

Open any Native Alpha app containing input fields (user names, passcodes, pins etc)

Long press field for context menu with paste

Result: pastable content is always URL for Webapp, (facebook.com, instagram.com etc) not clipboard content.

Expecting to be able to paste clipboard content.

This behavior makes logins challenging to impossible depending on clipboard content length.

**Comment by Fabeuss** [comment]
Same here with **Bitwarden**...
I can't paste 2fa code or password, very annoying...
Please remove the app menu and leave the original android text selector.
Thanks for your great app !

**Comment by programmerPhysicist** [comment]
Yes, being able to paste would be great.

**Comment by cylonid** [comment]
You can fallback to the actual right-click behaviour by using the "More" button, then "Select text". I see that this label is misleading, as selecting text is not the only thing you can do with the default context menu, e.g., paste text as you requested is also possible. The label is changed in the next release.

In addition, the Web App gets a setting to permanently disable the Native Alpha custom context menu.
