### ISSUE TITLE
Feature request: have all webapp-specific settings available as global settings too

### ISSUE THREAD

**Issue by VR-25** [cylonid/NativeAlphaForAndroid#12]
Let's say I want all webapps to send the "Save-Data: on" header, block images and cookies by default.
Instead of having to configure them individually, global settings would be much more convenient and efficient.

**Comment by cylonid** [comment]
This will be included in the next release: The user can set a general, global set of Web App settings. For every Web App, there is an option to override the global settings.

**Comment by cylonid** [comment]
Done.
