### ISSUE TITLE
Feature request: reorder & group apps

### ISSUE THREAD

**Issue by LittleFreak** [cylonid/NativeAlphaForAndroid#120]
After adding more and more websites to nativeAlpha, the list becomes cluttered. 
It would be great, if we could reorder the list of website apps.
Creating custom groups like news/gaming/... Would be also support a more intuitive and clean UI.

**Comment by cylonid** [comment]
@LittleFreak Reordering is included in the newest release :tada:
Grouping might come with a bigger UI overhaul, although I have to admit that it's not much of an issue for me personally as my No 1 way to open Web Apps is over desktop shortcuts which you can align and group as you wish.

**Comment by LittleFreak** [comment]
It's a good start, much appreciated 😊
> Grouping might come with a bigger UI overhaul, although I have to admit that it's not much of an issue for me personally as my No 1 way to open Web Apps is over desktop shortcuts which you can align and group as you wish.

True, but that would be at least to much at my homescreen 😇
I rather use the context menu entry in f my lauchner, to start native@
Or just the app icon itself to boot. 
Implementing the grouping feature would be awesome
