### ISSUE TITLE
Just a question. (can close the issue)

### ISSUE THREAD

**Issue by MichaelDevon** [cylonid/NativeAlphaForAndroid#125]
How are sites isolated from eachother? Do sites share cookies like logging into gmail logs into youtube, or are different sites defined in the app completely independent and isolated? Are using 2 sites for example like using them in two different browsers? Can i buy the paid version without the play store if the one from github doesnt have this?

**Comment by cylonid** [comment]
In the regular version, the data between apps is not isolated, so it works like a regular browser.
In the Plus version, there is the option to enable sandboxing, yes. 

Currently, the Plus version is not readily available outside Google Play. I hope to be able to change this in 2024, in the mean time you might give it a shot and compile the app yourself using this repository. Everything is open-source, including the paid features.

**Comment by MichaelDevon** [comment]
I tried to do it, but ive failed. Never compiled an apk, only x86 programs. What are the build instructions? 
Do i need an older android studio? The latest one tells me something about target api too low, and after i fix that there are like 20 other errors.

**Comment by nain-F49FF806** [comment]
@MichaelDevon In `app/build.gradle` under dependencies, look for the following line

```
implementation 'org.adblockplus:adblock-android-webview:5.0.1'
```

change that to 

```
implementation 'org.adblockplus:adblock-android-webview:+'
```

That resolved the build issues for me. 

Version 5.0.1 of the dependency seems to be locked behind authentication. 
By making the version flexible it will pull whatever is available.

**Comment by MichaelDevon** [comment]
> @MichaelDevon In `app/build.gradle` under dependencies, look for the following line
> 
> ```
> implementation 'org.adblockplus:adblock-android-webview:5.0.1'
> ```
> 
> change that to
> 
> ```
> implementation 'org.adblockplus:adblock-android-webview:+'
> ```
> 
> That resolved the build issues for me.
> 
> Version 5.0.1 of the dependency seems to be locked behind authentication. By making the version flexible it will pull whatever is available.

Thank you! Ill try that.

**Comment by MichaelDevon** [comment]
> @MichaelDevon In `app/build.gradle` under dependencies, look for the following line
> 
> ```
> implementation 'org.adblockplus:adblock-android-webview:5.0.1'
> ```
> 
> change that to
> 
> ```
> implementation 'org.adblockplus:adblock-android-webview:+'
> ```
> 
> That resolved the build issues for me.
> 
> Version 5.0.1 of the dependency seems to be locked behind authentication. By making the version flexible it will pull whatever is available.

This is unfortunately not working anymore.
Circular progressbar also cant resolve and your method works there but adblockplus fails no matter what i do.
