### ISSUE TITLE
AdBlock+WebView Implementation Version Issue

### ISSUE THREAD

**Issue by cradihidau** [cylonid/NativeAlphaForAndroid#128]
Line 119 in the build.gradle script of the app module is ```implementation 'org.adblockplus:adblock-android-webview:5.0.1'``` but version 5.0.1 is not retrievable. This causes the app to be unable to build; removing the implementation results in a non-functional app.

Changing the version to + as suggested [here](https://github.com/adblockplus/libadblockplus-android) solves the issue, i.e: ```implementation 'org.adblockplus:adblock-android-webview:+'```

Currently, version 4.4.0 seems to be the latest retrievable version and using ```implementation 'org.adblockplus:adblock-android-webview:4.4.0'``` also solves the issue.

![H9v4j7C2ln8](https://github.com/cylonid/NativeAlphaForAndroid/assets/167648632/8e4f0171-bb7e-4e67-8425-50416d1664f8)

This is my first time attempting to build an APK from source so it may have been a mistake on my end, but luckily I now have a working extended release of the APK despite not being able to support the release due to not having the Google Play Store on my device.

**Comment by cylonid** [comment]
You are correct, the newer versions are no longer available publicly. It seems the whole library is discontinued unfortunately. For the meantime it should be fine to use 4.4, but it is obviously not a well-working solution...

**Comment by pixincreate** [comment]
but builds are failing, at least in my ci: 

```gradle
   > Could not find org.adblockplus:adblock-android-webview:4.4.0.
     Required by:
         project :app
```

for `circularprogressbar`, `v3.1.0` is the only available version.

however, `adblock` is unavailable. reverted a changes to see if it is available in `jitpack` at least, but no, asking for authentication there.

cc: @cylonid
