### ISSUE TITLE
Simulating right click

### ISSUE THREAD

**Issue by pachuco** [cylonid/NativeAlphaForAndroid#130]
Requesting ability to simulate a right click, either via long press directly, or from the context menu that was spawned by long press.
This would trigger native menu of webpage(if listener was added).

Discord is kinda ok as is, and this would make it better.

**Comment by cylonid** [comment]
You can fallback to the actual right-click behaviour by using the "More" button, then "Select text". I see that this label is misleading, as selecting text is not the only thing you can do with the default context menu. The label is changed in the next release.

In addition, the Web App gets a setting to permanently disable the Native Alpha custom context menu.
