### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by The8040** [cylonid/NativeAlphaForAndroid#131]
It's option to disabled the SSL certificate notification 

![Screenshot_2024-06-26-16-57-30-155.jpg](https://github.com/cylonid/NativeAlphaForAndroid/assets/122334076/dd038eab-f558-4ebd-a2ac-d71ae90d4081)

**Comment by WreckingBANG** [comment]
You can enable the Expert Settings in the SiteSettings and set Ignore SSL Errors if you are asking for that.
