### ISSUE TITLE
[bug]Text becomes invisible in dark mode.

### ISSUE THREAD

**Issue by atuy1219** [cylonid/NativeAlphaForAndroid#139]
Text becomes invisible in dark mode.
![Screenshot_20240822-201606](https://github.com/user-attachments/assets/b254bf98-df7d-4d74-adb3-f0ad2b66608b)
Android 15 Pixel 6a

**Comment by pachuco** [comment]
Adding to this: Icons in Discord sometimes switch from dark to light mode.

**Comment by atuy1219** [comment]
It seems that it was a bug in Android 15

**Comment by pachuco** [comment]
> It seems that it was a bug in Android 15

Is it?
I have android 13, and inverted graphics have been problem to me only since last Native Alpha update.
Oh wait, you said text...

**Comment by atuy1219** [comment]
Yes, but in my environment there is no problem with the disccode icon.
I think you should try opening a new issue.
