### ISSUE TITLE
Feature Request: Indicate refresh action

### ISSUE THREAD

**Issue by Stimmenhotel** [cylonid/NativeAlphaForAndroid#14]
While using the refresh gesture and in the future the automatic refresh it is not visible if the site is refreshing right now.
Maybe adding a loading bar above or below the website would make it more visible why the user input is not handled properly.

Another use case:
While on slow internet connection I don't know if my refresh gesture was successful and could happen in to many tries doing a refresh.
Instead the bar will show and I know I have to wait until it finishes.

Optional:
1. defining accent color per app or global, maybe using androids accent color? 
2. Using a few pixels for just indicating refresh action and the rest to indicate the progress. [Example](https://user-images.githubusercontent.com/15821524/101354115-f0ba7980-3894-11eb-919b-56c82c19292f.png)

**Comment by cylonid** [comment]
Good idea, a progress bar at the bottom will be added in the next release.

**Comment by cylonid** [comment]
Released in v0.85
