### ISSUE TITLE
[feature] copy (and maybe also edit) URL in settings dialog

### ISSUE THREAD

**Issue by pejobo** [cylonid/NativeAlphaForAndroid#142]
As the title says. When the path or domain of a resource changes the current process of updating it really cumbersome: Delete the app, create a new one, add the shortcut. It would be nice to be able to just adjust the URL. If this is not possible, at least the option of copying the URL from the setting dialog would help. This would ease the process of creating the new app entry. Yes, you can open the app and copy the URL from there (if the app is not doing a 404 redirect at least), but this step would be then eliminated, since you are in the settings dialog anyways.

**Comment by cylonid** [comment]
You can adjust the URL. It's just something I don't think many average users would do, so it's inside "Expert settings" section.
