### ISSUE TITLE
Feature request: Add an option to disable SSL Warning

### ISSUE THREAD

**Issue by Lythed** [cylonid/NativeAlphaForAndroid#16]
Hi,
since latest release when opening some websites, I get spammed with "Potential security threat" Warning and even when clicking "Load Anyway", these are always showing when restarting the app and/or when a new page is loaded, its pretty annoying and an option to disable this would be really appreciated! :)

**Comment by cylonid** [comment]
Hi, can you give examples?

**Comment by Lythed** [comment]
> Hi, can you give examples?

Here are some:
xda-developers.com
asos.com
amazon.fr (.com too and maybe others)
simplenote.com

**Comment by cylonid** [comment]
I cannot reproduce this problem. Which WebView implementation are you using, latest update installed? Otherwise I'd suggest to backup the Native Alpha data and reset all appdata.

**Comment by Lythed** [comment]
> I cannot reproduce this problem. Which WebView implementation are you using, latest update installed? Otherwise I'd suggest to reset the app data (create a backup of your Web Apps first).

Im using Android System WebView 88.0.4324.93
Downgrading to 86.0.4240.185 and enabling/disabling Chrome did not fix the issue.
I have cleared all data from the app and Im having the same issue sadly.

Im running Android 11/OnePlus 7T (HD1903) if that's can help.

**Comment by cylonid** [comment]
In general, these certificates are managed on device-level. But you are sure this issue occurs only in Native Alpha, starting from v0.85? If you open XDA in Chrome or an older version of NA, it works flawlessly?

**Comment by Lythed** [comment]
> In general, these certificates are managed on device-level. But you are sure this issue occurs only in Native Alpha, starting from v0.85? If you open XDA in Chrome or an older version of NA, it works flawlessly?

Hi, after further test, this "issue" is present in Native Alpha 0.82+. This is working flawlessly in version 0.81;
I updated to latest OnePlus Open Beta (so Android 10 to 11). I did not mention that ~~because im dumb~~ and I was having no issue with Android 10.

Though, I have no issue when trying these websites with Chrome

**Comment by cylonid** [comment]
@Lythed Can you try whether it works in a similar WebView application such as [TobyKurien's WebApp](https://github.com/tobykurien/webapps)?
Did you have a look on the list of certificates stored on your device? I suppose there are some missing certificates on this  OnePlus Beta ROM, a user reported the same issue using a custom ROM [on XDA](https://forum.xda-developers.com/t/app-8-0-native-alpha-transform-any-website-into-native-fullscreen-web-apps.4132849/page-2#post-83665469) a while ago.

**Comment by Lythed** [comment]
> @Lythed Can you try whether it works in a similar WebView application such as [TobyKurien's WebApp](https://github.com/tobykurien/webapps)?
> Did you have a look on the list of certificates stored on your device? I suppose there are some missing certificates on this OnePlus Beta ROM, a user reported the same issue using a custom ROM [on XDA](https://forum.xda-developers.com/t/app-8-0-native-alpha-transform-any-website-into-native-fullscreen-web-apps.4132849/page-2#post-83665469) a while ago.

Same error with [TobyKurien's WebApp](https://github.com/tobykurien/webapps). This seem to be an issue with localhost certificate. (See [Screenshot_20210129-211038](https://user-images.githubusercontent.com/35495389/106331064-9af6c200-6284-11eb-86db-177c322ed902.jpg))
 Checked some things here and there and I did not found a proper way to trust "localhost certificate"? And yes, I checked my certificates, I have a bunch of these in my list but nothing weird in this one I guess

Anyway this is an issue with my device I guess I will try to fix that later this is not really important, I can always click "Load Anyway"

**Comment by RkcCorian** [comment]
I use ioBroker with https connection and without certificate. I would like to use my visualisation via your app (which I like much). But because of this I also get the SSL errors. There is an option in other apps (e.g WallPanel) to ignore SSL errors. Please add this also in your app, otherwise I allways get with your app those "ugly" SSL error as I do not invest at the moment in a certificate just to access my local visualisation. Many many thanks!!!! :-)

**Comment by cylonid** [comment]
The next release will include an option to disable the SSL check for single Web Apps. However, for security reasons this setting cannot be set globally, i.e., the user has to actively disable the check for a single app inside the Web App settings.

**Comment by cylonid** [comment]
Done.
