### ISSUE TITLE
Feature Request: Do not reload the whole page in case of switching between portrait and horizontal mode

### ISSUE THREAD

**Issue by RkcCorian** [cylonid/NativeAlphaForAndroid#18]
I use a visualisation (JARVIS) from my ioBroker which is a web page. When I change my phone from portrait to landscape mode (or the other way around) it is loading the whole page again. I compared with the app "WallPaper" where this does not happen. Please make this available in your app as you app is nice for the "like an app" feeling. Many thanks!

**Comment by cylonid** [comment]
This will be fixed in the next release.

**Comment by cylonid** [comment]
Done.
