### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by haarp** [cylonid/NativeAlphaForAndroid#21]
Hey,

I think this app should meet the [Policy for inclusing in F-Droid](https://f-droid.org/docs/Inclusion_Policy/). Would you be interested in that? It's an alternative store for Free Software on Android. Inclusion there would make the app more visibile and accessible, I think.

[Here](https://f-droid.org/en/docs/FAQ_-_App_Developers/) are some more resources. Unfortunately I don't know much about the procedures myself.

In the interim, [Izzysoft](https://apt.izzysoft.de/fdroid/index/info) also distributes many Open-Source apps by taking the apks directly from their corresponding repositories, so that might also be worth checking out. But inclusing in Fdroid would still be better.

Thanks a lot!

**Comment by cylonid** [comment]
In fact, I already had submitted an inclusion request to F-Droid but decided to put it on hold a while ago. While I absolutely support the idea behind F-Droid, I discovered various caveats which brought me to the decision not to use it in the foreseeable future. 

However, I am happy to announce that the app should be available on Google Play soon :slightly_smiling_face:

**Comment by haarp** [comment]
Alright, I see! I've put in a request for inclusion in Izzy's repository, hope you don't mind. This repo works with the same F-Droid clients, but takes the apks directly here from Github.

https://gitlab.com/IzzyOnDroid/repo/-/issues/160

**Comment by cylonid** [comment]
No, I don't mind - I'd be happy if the request is accepted. A problem I saw is that the APK size is larger than the stated limit (unfortunately, the AdBlock libs take quite some space) but maybe they will accept it nonetheless.

**Comment by haarp** [comment]
Yes, you're right. The size currently prevents inclusion. But having separate apks per architecture would solve that.

**Comment by Matthew-Hine** [comment]
Hey, in case you haven't seen it, the maintainer behind the Izzy f-driod repository rejected this solely based on file-size 

> Afraid not: Tha APK size (63M) is more than twice of this repo's limit (30M per app)  If you'd make an ARM only APK, that should be less than 15M (at least that's the ZIP size when I remove the x86* libs) and thus would fit the size criterium. My library scanner confirms the other criteria should fit.

@cylonid just want to say a massive thank you for putting in the time to making this application - Can you reconsider not trying to get this application into the f-droid store or expand on what your personal problems are with f-droid?

**Comment by cylonid** [comment]
The app is now hosted by [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.cylonid.nativealpha).
Find information how to add this repository with your F-Droid client [here](https://apt.izzysoft.de/fdroid/index/info).

**Comment by licaon-kter** [comment]
@cylonid 
> I discovered various caveats which brought me to the decision not to use it in the foreseeable future.

Care to expand?
