### ISSUE TITLE
select custom icon fails if an icon could not be retrieved in the first place

### ISSUE THREAD

**Issue by citizenserious** [cylonid/NativeAlphaForAndroid#28]
Hi folks,

I tried to download and select an icon manually for the webpage https://www.rain-alarm.com/ because an icon could not be retrieved.
So I downloaded https://www.rain-alarm.com/img2/launcher_transparent_white_64.png and tried to set it as an icon.
It is shown in the shortcut icon of the app, but when clicking on the OK button it disappears for the launcher. 
I also tried it with a ico file.
When I set the exact same png for a other website, where an icon could be retrieved for example https://check.torproject.org/ it works.

v1.01 from IzzyOnDroid on Android 11 LOS with the Shade launcher.

Thanks for helping.

**Comment by cylonid** [comment]
Hi,
cannot be reproduced, not even using that specific launcher. What exactly do you mean by "it disappears for the launcher"? Is no shortcut created at all or is the shortcut creation successful but with the default grey Native Alpha shortcut icon?

**Comment by citizenserious** [comment]
Odly after a restart of my phone it now works, don't now why.
