### ISSUE TITLE
Not working with Flask port

### ISSUE THREAD

**Issue by gewinh** [cylonid/NativeAlphaForAndroid#3]
Tried the url that I use for running python scripts via flask eg. https://domainname:5000/login this url works with chrome and I can create desktop icons and run the app. However, with nativealpha, I just get a blank screen. Using v0.81 on Android 9. Really like your app idea, hope you can resolve this.

**Comment by cylonid** [comment]
@gewinh Custom ports should work in general. Can you send me the URL to cylonid@gmx.at? No login credentials required, I just need to see whether the login screen loads.

**Comment by cylonid** [comment]
Issue caused by SSL configuration problem.
