### ISSUE TITLE
Request: Immersive mode

### ISSUE THREAD

**Issue by bladeslapper** [cylonid/NativeAlphaForAndroid#30]
I have just come across your app because I have a need for it for the first time and I actually can't believe that this has not been done before! Well done!

Would it be possible to have the option to open a page in one of the immersive modes? Ideally Sticky Immersive?
Hiding all the menu and status bars from around the screen would make it truly full screen and so very useful to present data from a website on an android device in a really tidy way.

I would also like the idea of forcing the screen to stay awake but I will post another request for this.

Keep up the good work

**Comment by cylonid** [comment]
Feature is available in Native Alpha Plus :wink:

**Comment by bladeslapper** [comment]
perfect, thanks
