### ISSUE TITLE
Request: Force screen on and not timeout

### ISSUE THREAD

**Issue by bladeslapper** [cylonid/NativeAlphaForAndroid#31]
It would be brilliant if you are able to natively force the Native Alpha webpage to force the screen to stay on and also to not timeout!
Developer options can be used to keep the screen on whilst charging which is good but it still dims after XX minutes due to the timeout feature. Apps have the ability to prevent this so having it an option of NativeAlpha would be awesome.

**Comment by cylonid** [comment]
Feature is available in Native Alpha Plus :wink:

**Comment by bladeslapper** [comment]
brilliant!
