### ISSUE TITLE
Request: multiple instances per service.

### ISSUE THREAD

**Issue by stpnwf** [cylonid/NativeAlphaForAndroid#36]
Currently if you are logged into a website if you create another instance of that same website it will also be logged in the same account as the first instance.

Would it be possible to add the ability for users to log into more than one instance of a service at the same time? This would be particularly useful to websites such as reddit, twitter, pinterest, etc where users may have more than one account. It is the case for me at least, and this would be very helpful.

I am unsure if sandboxing can be achieved via the Android WebView, but I have my fingers crossed, as I believe this would improve the already great UX of the app.

**Comment by cylonid** [comment]
Implemented as part of Native Alpha Plus :slightly_smiling_face:
