### ISSUE TITLE
Can not install on firestick , sideload failed

### ISSUE THREAD

**Issue by sacuar** [cylonid/NativeAlphaForAndroid#41]

**Comment by L96Github** [comment]
Neither can I in my Samsung Tab S2. 

Error says: 

> "There was a problem while parsing the package" 


"Install from unknown sources" is enabled and I have tried all 3 apk files for v1.01

**Comment by neilsimp1** [comment]
Same for me on a Samsung Tab S4.
I tried versions back to 0.8 and none would work. I'm guessing because it's a much older version of Android?

**Comment by cylonid** [comment]
Correct, the minimum version is Oreo (8.0). Somehow this information got lost from the FAQ, I'll readd it.
I don't know about Fire OS, it may work for FireOS 7+ but I have no means of testing it.

But even if the app would start, I cannot guarantee that the Amazon WebView is fully compatible.
