### ISSUE TITLE
Every website shows unstrusted SSL certificate popup

### ISSUE THREAD

**Issue by dyeray** [cylonid/NativeAlphaForAndroid#43]
Hi!

I'm going to open this ticket, although there is now a workaround ( https://github.com/cylonid/NativeAlphaForAndroid/issues/37 ) it would be nice to get to the root cause on why on some smartphones every website shows SSL certificate errors.

I've tested the latest version of Native Alpha, both on LineageOS and crDroid. These are clean installation of the roms, with no google libraries installed.

The logs show errors like these:

11-29 18:38:16.782 E/chromium(28787): [ERROR:ssl_client_socket_impl.cc(976)] handshake failed; returned -1, SSL error code 1, net_error -202

Webview implementation: Android System WebView 95..0.4638.50

**Comment by dyeray** [comment]
I was troubleshooting this. It is caused by using AdAway, since it redirects https connections to ad servers to a fake server on localhost.

**Comment by groovenectar** [comment]
> I was troubleshooting this. It is caused by using AdAway, since it redirects https connections to ad servers to a fake server on localhost.

Nice sleuthing!
