### ISSUE TITLE
Unable to use application with LAN addresses

### ISSUE THREAD

**Issue by re3lex** [cylonid/NativeAlphaForAndroid#48]
Hi,

I want to use application with site hosted on my local network (like `https://nas/some-path`), but application shows the error "Please enter a valid web address":
![изображение](https://user-images.githubusercontent.com/4106391/150125862-89177659-b170-4424-8b5a-e679bacaaeaa.png)

**Comment by cylonid** [comment]
Fixed in release v.1.2.0, you are free to use local addresses. Keep in mind to prefix your URL with http if your site is not available with https
