### ISSUE TITLE
[Feature request] Website share function / copy link

### ISSUE THREAD

**Issue by BluePixel4k** [cylonid/NativeAlphaForAndroid#49]
A support of the sharing function of websites. 
For example, sharing to the clipboard does not work on Amazon.
<img src="https://user-images.githubusercontent.com/77979781/152582886-5d012b3a-2747-4fd5-960a-98000e4183ea.png" width="300" />

In general, a way that you can always copy the URL would be great. Chromium (Brave) does it via the notifications.
<img src="https://user-images.githubusercontent.com/77979781/152583816-610a1987-2831-4de3-9d4b-5451dbeacf88.png" width="300" />

**Comment by cylonid** [comment]
This is now implemented with v1.3.0
