### ISSUE TITLE
True isolation?

### ISSUE THREAD

**Issue by mattdrepo** [cylonid/NativeAlphaForAndroid#50]
I might be missing something here, but I really wanted to be able to run multiples of websites (especially facebook for example).  When I create another facebook, it loads the previous.  This would be really useful for multiple accounts on a system as webapps.  Can this be done?  And if not, can I ask for this as a feature request.  Great little app!

**Comment by cylonid** [comment]
Sandboxing is implemented as part of Native Alpha Plus :slightly_smiling_face:
