### ISSUE TITLE
Fullscreen hides bottom button menu

### ISSUE THREAD

**Issue by mikromCZ** [cylonid/NativeAlphaForAndroid#58]
when I open the app, bottom buttons (home, back, recent apps) is covered. I can reveal it by swiping over bottom edge, but it is annoying (with phone case).
can it be disabled somehow (optionally)?

Samsung S10e, Android12

Thanks

**Comment by pedrom34** [comment]
same for me.

**Comment by cylonid** [comment]
Should be fixed with latest release.

**Comment by karthickspk08** [comment]
actually I wanted the navigation buttons hidden,in instagram bottom bar are not visible
because of navigation buttons,lets make it optional

**Comment by cylonid** [comment]
@karthickspk08 As this is apparently causing some issues like navigation buttons overlapping with the content on various devices, I will probably revert the default behaviour to pre-1.3.0
