### ISSUE TITLE
Unable to add custom shortcut icon

### ISSUE THREAD

**Issue by DreadedLama** [cylonid/NativeAlphaForAndroid#62]
In case Native alpha fetches icons from the provided site, if we want to choose a custom icon in such case, the shortcut is still created with the icon fetched by Native alpha.
Example - Add URL as twitter.com. Native alpha fetches the icon, now choose a custom icon, select any icon and create the shortcut. The shortcut will be created with the original fetched icon.

**Comment by cylonid** [comment]
Sounded like a bug on first sight, but I cannot reproduce that.
Can you elaborate on your setup and maybe provide the custom file you tried?

**Comment by DreadedLama** [comment]
Tried to reproduce the issue now. Worked fine. May have been an issue with the icon I was trying.
