### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Reporter1** [cylonid/NativeAlphaForAndroid#70]
Hi is it possible you can provide how to build source to apk please.

Thanks.

**Comment by cylonid** [comment]
There is nothing special about building Native Alpha.

Any Android tutorial will do.

**Comment by Reporter1** [comment]
Hi I managed to build Native Alpha using some instructions from a Google search, which is fine. 
It would've been nice to see them added on the page but it's fine it isn't. I guess it encourages some users to purchase and support you.
