### ISSUE TITLE
No Shortcut Icon for aljazeera.com

### ISSUE THREAD

**Issue by quwepiro** [cylonid/NativeAlphaForAndroid#71]
The favicon for https://www.aljazeera.com cannot be retrieved.
As this site is a very big news site, it could be that this issue is related to the app and not to a missing favicon of the website.

**Comment by cylonid** [comment]
There is no high-resolution icon available, therefore the icon cannot be retrieved automatically. 
You can always download a suitable icon and then set it manually.
