### ISSUE TITLE
Is NativeAlpha still in development?

### ISSUE THREAD

**Issue by Terkyz** [cylonid/NativeAlphaForAndroid#73]
Just found this wonderful app, although I know that no updates in a while does not mean it is obsolete, but I am interested to know if it will still receive more updates.

**Comment by cylonid** [comment]
It is, definitely. 

A new update will follow soon.

**Comment by Terkyz** [comment]
> It is, definitely.
> 
> A new update will follow soon.

How can I buy NativeAlpha Plus without going to Google Play? I am interested in its extra features but I don't have or want to use Google services, is there an alternative method?

**Comment by cylonid** [comment]
There is no way to buy Native Alpha Plus outside GP currently. [Further discussion](https://github.com/cylonid/NativeAlphaForAndroid/issues/57)

You can however build Native Alpha including Plus features locally for yourself if you wish to.

**Comment by Terkyz** [comment]
> There is no way to buy Native Alpha Plus outside GP currently. [Further discussion](https://github.com/cylonid/NativeAlphaForAndroid/issues/57)
> 
> You can however build Native Alpha including Plus features locally for yourself if you wish to.

I have 0 experience compiling/building, is there a guide to do this?

**Comment by cylonid** [comment]
Then it's a nice oppurtunity to learn :wink: 
There is no specialized guide for Native Alpha, any Google search "android studio build apk" will do.

**Comment by Terkyz** [comment]
> Then it's a nice oppurtunity to learn wink There is no specialized guide for Native Alpha, any Google search "android studio build apk" will do.

I already did it and honestly it was quite easy but I don't see the Plus options, and all the apks have the label "standard" their name, I built the wrong version?

**Comment by cylonid** [comment]
If you you want the Plus features, you will need to selected that build recipe
