### ISSUE TITLE
Login with Google - Error 403: disallowed_useragent 

### ISSUE THREAD

**Issue by christiaangombert** [cylonid/NativeAlphaForAndroid#77]
I need to login with Google credentials for a website. Sadly I now get Error 403: disallowed_useragent

This will occur because the Android app makes a login request that Google rejects. The most common reason for this rejection is an unauthorized browser agent (the app is using a deprecated browser agent that Google no longer accepts).

**Comment by cylonid** [comment]
I am aware of this issue - Google actively disallows the login to its services with applications which use their own WebView.
In the next release, this will be handled accordingly.

For further details, read this: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html
