### ISSUE TITLE
Amazon fav icon not working 

### ISSUE THREAD

**Issue by Stimmenhotel** [cylonid/NativeAlphaForAndroid#80]
Just installed native alpha plus 1.3.0 and tried to add Amazon.de as a WebApp.
But the favicon can't be received anymore.

It seems the hard coded link for the icon is down / Access forbidden:
https://s3.amazonaws.com/prod-widgetSource/in-shop/pub/images/amzn_favicon_blk.png

Already disabled my AdBlock, but it seems not to be the one blocking the access.

**Comment by cylonid** [comment]
Thanks for brining it to my attention, I should probably write a test to make sure the hardcoded URLs are working.

**Comment by Stimmenhotel** [comment]
No Problem. Thank you for your app.
