### ISSUE TITLE
Can't add a new Web App, instant crash

### ISSUE THREAD

**Issue by TomBonnot** [cylonid/NativeAlphaForAndroid#81]
Since 1.3.0, I have an app crash whenever I try to add a web app, for any website.
Running on Pixel7 downloaded from Play Store.
EDIT : I did export my previous setting from my last web app, and after that the bug appears.
List of my previous apps : 
Instagram
Twitter 
Twitdeck
DeviantArt
ArtStation
AdGuard DNS 
Gather 
Wikipedia
Nitter

**Comment by TomBonnot** [comment]
It appears that my global apps settings are somehow... disabled ? Everything is grey and I can’t modify it.

**Comment by karmakarmeghdip** [comment]
Same problems here

**Comment by cylonid** [comment]
Sorry for the inconvenience caused, patch is own its way.
