### ISSUE TITLE
Webview under status bar and navigation buttons

### ISSUE THREAD

**Issue by Prazola** [cylonid/NativeAlphaForAndroid#84]
Hi,

after upgrading to 1.3.0 the webapps are rendering in fullscreen, and the status bar and the navigation buttons bar are covering parts of the webview.
This happens with my Umidigi S5 pro (stock android 10) but doesn't with my Mi 10 Lite 5G (lineageos 19.1).

The issue persists with 1.3.1.

Let me know how to provide you more info.
![native](https://user-images.githubusercontent.com/4884858/203862548-eea9a748-237c-4391-8da4-c042720c98ed.jpg)

**Comment by mclarence554** [comment]
I have the same issue with Twitter ( Android 8.1, Oppo f9 pro)
![Uploading Screenshot_2022-11-25-09-15-18-20.png…]()

**Comment by cylonid** [comment]
Relates to #58.
Seems like the new behaviour doesn't work as nicely as it does on Samsung on all devices. 

What was the behaviour on your devices before the v1.3.0 update? Did it always show the bottom bar without messing up the screen OR did it only reveal the bottom bar if you swiped on the edge (which was the case for Samsung)?

**Comment by Prazola** [comment]
It always showed the bottom bar.

**Comment by CodeCubeNeo** [comment]
I also have this problem (rendered web page under status bar and navigation buttons). I have a Huawei Mate 9 with Android 9. Hope this gets fixed soon, because this makes the app fairly harder to use.

**Comment by TurkerTunali** [comment]
I also have this problem on my Huawei Mate 10 Pro.

**Comment by aglidden** [comment]
I was having the same problem. Running `adb shell settings put global policy_control immersive.full=com.cylonid.nativealpha` fixed it on my Samsung as per [this tutorial](https://www.howtogeek.com/302194/how-to-force-any-android-app-into-fullscreen-immersive-mode-without-rooting/).

**Comment by cylonid** [comment]
Sorry for keeping this open so long, the old behaviour will be restored in the next release, with the new behaviour of forcing the system menus being an optional global setting.

**Comment by raShMan777** [comment]
i still have this problem with 1.4.0 on a pixel 9 pro xl.
