### ISSUE TITLE
pages are displayed fullscreen without hiding top and bottom Android bars

### ISSUE THREAD

**Issue by ghost** [cylonid/NativeAlphaForAndroid#85]
1. Add booking.com
2. Open it

Page is displayed considering the fullscreen size of the phone, but without hiding Android's bars

![Screenshot_2022-11-25-07-27-14-67](https://user-images.githubusercontent.com/15078341/203915437-f3e7b83e-ae60-4566-8f82-a51afb86e242.jpg)

Android 10
NativeAlpha 1.3.1

**Comment by marcoparravano** [comment]
Same problem for me on Android 10.

**Comment by cylonid** [comment]
Sorry for keeping this open so long, the old behaviour will be restored in the next release, with the new behaviour of forcing the system menus being an optional global setting.
