### ISSUE TITLE
Add ability to open multiple webapps in different window

### ISSUE THREAD

**Issue by Scripterr** [cylonid/NativeAlphaForAndroid#9]
Nice app you have created congrats and I would love to see it maintained.
The feature I'm asking is present in most full fledged firefox and chromium browser such as bromite, Vivaldi, brave, etc. This helps in browsing the multiple web apps side by side and not reloading every time you open different webapp.
It is problematic that if you switch to a different webapp it discards that site and the new site opens in it's place, would love to see this solved. If you need more information please ask.
(Sorry for bad english not a native speaker)

Thank you.

**Comment by cylonid** [comment]
@Scripterr This is fixed with release v0.83
