### ISSUE TITLE
Dark UI setting

### ISSUE THREAD

**Issue by fohfuu** [cylonid/NativeAlphaForAndroid#93]
I've seen "dark mode" mentioned around the Github but can't find out how to activate it. I don't mean about turning it on or off for websites - just for the app UI

Options that have worked for forcing ""automatic"" dark modes (e.g. developer settings > night mode, Dark Theme app by PH Studios) work for other apps but do not make Native Alpha switch to a dark theme. I don't know if it's supposed to be automatic or not but I can't make it switch.

It would be useful if this was a switchable option in the global app settings.

Please let me know if there's something I'm missing.

Nokia 8 - Android 9
Version 1.3.1 (IzzyOnDroid)

**Comment by cylonid** [comment]
As pointed out, the Dark Mode option is only supported with Androd 10 or higher.
